spring:
  application:
    name: propostas
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/PropostaRealm}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/PropostaRealm/protocol/openid-connect/certs}

app:
  nome: ${NOME_SERVICO:propostas}

sistemas:
  analise-financeira:
    url: ${ANALISE-FINANCEIRA_URL:http://localhost:9999}
  cartoes:
    url: ${CARTOES_URL:http://localhost:8888}

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      aplicacao: ${NOME_SERVICO:propostas}
      ambiente: ${AMBIENTE:desenvolvimento}

opentracing:
  jaeger:
    # Jaeger - Habilita ou não
    enabled: ${JAEGER_ENABLED:true}
    # Jaeger - Nome do serviço
    service-name: ${spring.application.name}
    # Jaeger - Endereço para enviar os metadados (trace, span, etc)
    http-sender:
      url: ${JAEGER_ENDPOINT:http://localhost:14268/api/traces}
    # Jaeger - Tipo de amostragem (probabilístico) e sua configuração (1 = 100%)
    probabilistic-sampler:
      sampling-rate: ${JAEGER_SAMPLER:1}