spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proposta?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: eduardo
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
