spring:
  datasource:
    url: jdbc:mysql://${DB_NAME:localhost}:3306/proposta?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USER:eduardo}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

feign:
  client:
    config:
      AnaliseFinanceiraClient:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: basic
      CartaoClient:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: basic

logging:
  level:
    org:
      springframework:
        security: DEBUG