spring:
  datasource:
    url: jdbc:mysql://localhost:3306/proposta?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USER:eduardo}
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
