version: 2
jobs:
    build:
        docker:
            - image: circleci/openjdk:11-browsers-legacy
              environment:
                  DB_USER: root
                  DB_PASSWORD: ""
                  MAVEN_OPTS: -Xmx3200m
            - image: circleci/mysql:latest
              environment:
                  MYSQL_ALLOW_EMPTY_PASSWORD: yes
                  MYSQL_ROOT_PASSWORD: ''

        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: Wait for Database Connection
                command: dockerize -wait tcp://localhost:3306 -timeout 1m

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      - v1-dependencies-

            - run: mvn dependency:go-offline

            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            - run: mvn integration-test
